# why the need for congig.yaml ?

# artifacts is collection of folders
artifacts_root : artifacts

# STAGE 1: dataset config
data_ingestion:
  root_dir : artifacts/data_ingestion
  # URL for the dataset
  source_URL : https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion

  # stage 2: data validation
data_validation:
  root_dir : artifacts/data_validation
  STATUS_FILE : artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES : ["train","test","validation"]